version: '3.8'
services:
  app:
    build: .
    command: npx nodemon index.js
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=development
    working_dir: /app
