version: '3.8'
services:
  app:
    build:
      context: .
      target: production-stage
    ports:
      - "8080:80"
    env_file: 
      - ./.env
    environment:
      - PORT=80
    volumes:
      - .:/app
